### ISSUE TITLE
How do I get the URL of an item?

### ISSUE THREAD

**Issue by Benisthebest** [dzt/supreme-api#7]
How do I get the URL of an item? I am building a bot for a friend and I want the url of any item.

**Comment by Logfro** [comment]
Best solution would be to use the seek function and then get the url from the response

**Comment by Benisthebest** [comment]
How do you? The example doesn't show that.

**Comment by Logfro** [comment]
const category = 'jackets';
const keywords = "UNDERCOVER";
const style = 'Burgundy';

supreme.seek(category, keywords, style, (product, err) => {
    if (err) {
        console.log(err);
        return err;
    }
    console.log(product);
    console.log(product.title); // example => Supreme®/UNDERCOVER Wool Overcoat
});

actually it does, by "console.log(product)" it also outputs the url, then you just need to get the value from the array

**Comment by Benisthebest** [comment]
Thank you.
